# -*- coding: utf-8 -*-
# Form implementation generated from reading ui file 'Keylogin.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(719, 478)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(-1, 10, 10, 10)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dropShadowFrame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.dropShadowFrame.setFont(font)
        self.dropShadowFrame.setStyleSheet("QFrame{\n"
"background-color:rgb(56,58,89);\n"
"color:rgb(220,220,220);\n"
"border-radius: 10px;\n"
"}")
        self.dropShadowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dropShadowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dropShadowFrame.setObjectName("dropShadowFrame")
        self.label = QtWidgets.QLabel(self.dropShadowFrame)
        self.label.setGeometry(QtCore.QRect(10, 50, 691, 61))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color:rgb(0, 85, 255);\n"
"}")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.label_decription = QtWidgets.QLabel(self.dropShadowFrame)
        self.label_decription.setGeometry(QtCore.QRect(-10, 120, 691, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.label_decription.setFont(font)
        self.label_decription.setStyleSheet("QLabel{\n"
"color:rgb(98,114,164)\n"
"}")
        self.label_decription.setTextFormat(QtCore.Qt.AutoText)
        self.label_decription.setScaledContents(False)
        self.label_decription.setAlignment(QtCore.Qt.AlignCenter)
        self.label_decription.setWordWrap(False)
        self.label_decription.setObjectName("label_decription")
        self.progressBar = QtWidgets.QProgressBar(self.dropShadowFrame)
        self.progressBar.setGeometry(QtCore.QRect(70, 330, 531, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"background-color : rgb(98,114,164);\n"
"color:rgb(200,200,200);\n"
"border-style:none;\n"
"border-radius:10px;\n"
"text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"border-radius:10px;\n"
" background-color:qlineargradient(spread:pad, x1:0.164773, y1:0.267, x2:1, y2:0, stop:0.215909 rgba(63, 29, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.loading = QtWidgets.QLabel(self.dropShadowFrame)
        self.loading.setGeometry(QtCore.QRect(80, 380, 541, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.loading.setFont(font)
        self.loading.setStyleSheet("QLabel{\n"
"color:rgb(98,114,164)\n"
"}")
        self.loading.setTextFormat(QtCore.Qt.AutoText)
        self.loading.setScaledContents(False)
        self.loading.setAlignment(QtCore.Qt.AlignCenter)
        self.loading.setWordWrap(False)
        self.loading.setObjectName("loading")
        self.created = QtWidgets.QLabel(self.dropShadowFrame)
        self.created.setGeometry(QtCore.QRect(-50, 420, 731, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.created.setFont(font)
        self.created.setStyleSheet("QLabel{\n"
"color:rgb(98,114,164)\n"
"}")
        self.created.setTextFormat(QtCore.Qt.AutoText)
        self.created.setScaledContents(False)
        self.created.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.created.setWordWrap(False)
        self.created.setObjectName("created")
        self.verticalLayout.addWidget(self.dropShadowFrame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<strong>Keylogx Application </strong>"))
        self.label_decription.setText(_translate("MainWindow", "<strong>Safe & Secure </strong>"))
        self.loading.setText(_translate("MainWindow", "Loading...."))
        self.created.setText(_translate("MainWindow", "<strong>Created</strong>: Vishal Dhanure"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
